# -*- coding: utf-8 -*-
"""ConversationalChatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1wNJkVbmXlP1F86LwWijUbLTLyO5n03
"""

# !pip install langchain
# !pip install openai

import os
os.environ["OPENAI_API_KEY"] = "sk-proj-8fRFBu6klzsZXbTuHaUWT3BlbkFJWkDq4qtEb8HOW3jzV8WD"
from langchain.chains.question_answering import load_qa_chain
from langchain.llms import OpenAI

llm = OpenAI(temperature=0.5)
# Task 1
def General_AI(query):
  response = llm(f"Your name is Kira, a virtual assistant to help people to solve queries.Answer of this query: {query}")
  return response

response = General_AI("Who are you?")
print(response)