# -*- coding: utf-8 -*-
"""ProgressayPdfQuery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mPajkmWulYwbX1hpd8lEuc3zK2AdvsAb

## PDF Query Using Langchain
"""

!pip install langchain
!pip install openai
!pip install PyPDF2
!pip install faiss-cpu
!pip install tiktoken

from PyPDF2 import PdfReader
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.text_splitter import CharacterTextSplitter
from langchain.vectorstores import FAISS

import os
os.environ["OPENAI_API_KEY"] = "sk-proj-qztoVSd9693Q5PAnTN3GT3BlbkFJgOAWSgo9YQVFgudnp6kh"

# provide the path of  pdf file/files.
pdfreader = PdfReader('/content/Performance Appraisal.pdf')

from typing_extensions import Concatenate
# read text from pdf
raw_text = ''
for i, page in enumerate(pdfreader.pages):
    content = page.extract_text()
    if content:
        raw_text += content

raw_text

# We need to split the text using Character Text Split such that it sshould not increse token size
text_splitter = CharacterTextSplitter(
    separator = "\n",
    chunk_size = 800,
    chunk_overlap  = 200,
    length_function = len,
)
texts = text_splitter.split_text(raw_text)

len(texts)

# Download embeddings from OpenAI
embeddings = OpenAIEmbeddings()

document_search = FAISS.from_texts(texts, embeddings)

document_search

from langchain.chains.question_answering import load_qa_chain
from langchain.llms import OpenAI

chain = load_qa_chain(OpenAI(temperature=0.8), chain_type="stuff")

query = "When self review procedure is starting, Please tell me date"
docs = document_search.similarity_search(query)
chain.run(input_documents=docs, question=query)

query = "Can you write a summary"
docs = document_search.similarity_search(query)
chain.run(input_documents=docs, question=query)

query = "Where Noman is born"
docs = document_search.similarity_search(query)
chain.run(input_documents=docs, question=query)